apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-admin
      initContainers:
        - name: install-docker
          image: docker:stable
          command: ["cp", "/usr/local/bin/docker", "/data/docker"]    
          volumeMounts:
          - name: docker
            mountPath: "/data"
        - name: install-kubectl
          image: hopa/my-kubectl
          command: ["cp", "/usr/local/bin/kubectl", "/data/kubectl"]    
          volumeMounts:
          - name: kubectl
            mountPath: "/data" 
        - name: chown
          image: alpine:latest
          command: ['sh', '-c', 'chmod 777 /var/jenkins_home']      
          volumeMounts:
          - name: data-disk
            mountPath: /var/jenkins_home
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
          volumeMounts:
              - mountPath: /var/run
                name: docker-sock
              - name: data-disk
                mountPath: /var/jenkins_home
              - name: docker
                subPath: "docker"
                mountPath: "/usr/local/bin/docker"
              - name: kubectl
                subPath: "kubectl"
                mountPath: "/usr/local/bin/kubectl"
      volumes:
          - hostPath:
              path: /var/run
              type: ""
            name: docker-sock
          - name: data-disk
            persistentVolumeClaim:
              claimName: jenkins-pvc
          - name: docker
            emptyDir: {}
          - name: kubectl
            emptyDir: {}
          - name: jenkins-home
            emptyDir: {}