apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - name: httpport
              containerPort: 8080
          volumeMounts:
            - name: jenkins-pv-volume
              mountPath: /var/jenkins_home         
      volumes:
        - name: jenkins-pv-volume
          persistentVolumeClaim:
              claimName: jenkins-pv-claim